spring:
  datasource:
     url:      ${DB_URL}
     username: ${DB_USERNAME}
     password: ${DB_PASSWORD}
#   url:      jdbc:postgresql://localhost:5432/postgres
#   username: postgres
#   password: Welcome

  jpa:
    database-platform:  org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none
      show-sql: true

    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation:  true

server:
  port: 5000

app:
  version:  1.0.0